### ISSUE TITLE
How to capture the registry listing information for the wallet the user selected?

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectModalFlutter#10]
Dealing with various wallets, I have found I cannot trust the wallet to populate the same data in the peer PairingMetadata as they do in the WalletConnect registry listing.  I am looking for a way to capture the registry listing that was tapped by the user in the WalletConnectModel

**Ask Ideally:**
- The registry metadata that was called
- The type of link (URI/Native) that was successfully launched so I can launch the wallet consistently.
- Even nicer if the plugin could save/restore that so I don't have to... but that's another story.

**Examples of data missing in PairingMetadata (compatibility challenges)**
* No app icons (empty list returned)
* No redirect URIs  (optional field)

I had hoped I could just start the app, and read in all the connected Peer's information from the plugin.  Now I can only _prioritize_ that, and fallback/supplement with the original listing.   (Or the latest listing if I needed to fetch by appId and there was a easy Explorer service apI to do that.)

**Comment by bobwith2bees** [comment]
Due to #11 - I am not sure even the listing Id from the v1 api is compatible with the published v3 api "id" for explorer.   Challenges of multiple teams running fast I suppose.

**Comment by Luzzotica** [comment]
Yeah, the discrepancies were frustrating for me as well.

The library should already provide solutions to number 1 and number 2 in your list.
That's what the `launchCurrentWallet` function is for. 
Maybe that only responds to problem 2 that you listed. Perhaps I can create something for the metadata as well so you can query the image and other data.

**Comment by bobwith2bees** [comment]
@Luzzotica  -  If you could make a variant of launchWallet that takes a topic and calls the correct wallet - you can support the case of 1 DApp connected to multiple wallets.

**Comment by Luzzotica** [comment]
Just adding the session topic to the launchWallet function wouldn't resolve the issue completely.
There are other issues with multiple wallets.

For example, what address should I provide when the user requests it?

It's not as simple as just putting a topic in there.
There are multiple other changes that would need to take place.
How many use cases are there for connecting with multiple wallets from one dApp?

I feel that it's such a niche use case, that if someone really wants it, they can just use the base library and implement custom things. This library isn't really built for it.

**Comment by Luzzotica** [comment]
I see the logic now.

This is something I will keep in mind. I'll see if there is a simple way to tackle all of these issues.
