### ISSUE TITLE
Explorer service calling undocumented APIs

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectModalFlutter#11]
FYI  - There are a 3  URI references in lib/services/explorer/explorer_service.dart that are not documented here: https://docs.walletconnect.com/2.0/cloud/explorer

* They all appear to take a projectId (to limit abuse), so I assume it was safe to call these out.
* Given the v1 in the path - these might already be deprecated? 

I just would like to avoid a surprise outage/firedrill that could be avoided.  Please sync with the Explorer team on this.  I would prefer the API to be documented, or the code updated to a documented version.

Specific ones I noticed:
* https://github.com/WalletConnect/WalletConnectModalFlutter/blob/ff604fda1e89835455bc9b303eae96b13afe870a/lib/services/explorer/explorer_service.dart#L85
* https://github.com/WalletConnect/WalletConnectModalFlutter/blob/ff604fda1e89835455bc9b303eae96b13afe870a/lib/services/explorer/explorer_service.dart#L192
* https://github.com/WalletConnect/WalletConnectModalFlutter/blob/ff604fda1e89835455bc9b303eae96b13afe870a/lib/services/explorer/explorer_service.dart#L199

P.S. It is totally possible I am looking at the wrong place.  The search box on  **https://docs.walletconnect.com/2.0/cloud/explorer** directs me to docs that don't exist.

**Comment by Luzzotica** [comment]
Noted.

I copied these endpoints from the javascript repo. I didn't work from the official documentation. I will follow up with them on this. Thanks for bringing it up!

**Comment by Luzzotica** [comment]
These endpoints are designed for internal use.

They aren't documented for public use for that reason.

That's the info I got back from WC team.

**Comment by bobwith2bees** [comment]
FYI - Just a comment that some /v1 endpoints had been announced end of life:

* https://docs.walletconnect.com/cloud/explorer#legacy-endpoints

Might be worth spot checking for impact.

**Comment by quetool** [comment]
Thanks @bobwith2bees! I'll take a look!
