### ISSUE TITLE
Missing example/sign/lib/models/eth/ethereum_transaction.g.dart

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectModalFlutter#12]
Looks like a model with Json Serialization preprocessing was introduced recently, without the corresponding generated code.

**Workaround** 
(these lines are in the top level project pubspec.yaml if my notes are too terse): 
In example/sign/pubspec.yaml
* Add   json_annotation: ^4.8.1 to dependencies
* Add   json_serializable: ^6.7.0 to dev_dependencies

From example/sign directory
```bash
flutter clean
flutter pub get
flutter pub run build_runner build --delete-conflicting-outputs
```

**Comment by Luzzotica** [comment]
Resolved.
