### ISSUE TITLE
Ethereum contract example

### ISSUE THREAD

**Issue by Hardu2203** [WalletConnect/WalletConnectModalFlutter#13]
Firstly thanks for this awesome repo, its better than sliced bread

Were you able to get the store contract to work?

I connected to a local ganache-cli chain and deployed the store contract to it.

I cannot see something clearly wrong?

I call the store function like this

![image](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/10627824/de380f3d-bbe9-4b5d-a4a1-ecea5e1c05ce)

And then I get back 

![image](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/10627824/40e51ea4-acd7-420c-a030-040044c15c5a)

The call works fine through remix 

![image](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/10627824/7dfe9029-d5b8-4619-94ab-29bf63ce69d2)

Any advice would be appreciated.

**Comment by Luzzotica** [comment]
My first thought is that perhaps the wallet is unpacking the transaction incorrectly and causing you issue.

Are you using MetaMask? It looks like you are. I have had issues with them not including required fields in the JsonRpcError object. I'll make the code nullable to resolve this issue, but technically that shouldn't be possible according to the JSON RPC spec.

**Comment by Hardu2203** [comment]
Hi Sterling,

Thanks for the quick responses! 😁 

Yes I am using metamask, I will keep on investigating to see if I can get it working somehow.

I wish I could see the index.android.bundle to see what is going on in line 3652.  

But it just errors on metamask's side and then the message gets sent back saying it failed, so this is a hard one to solve.

**Comment by Luzzotica** [comment]
The newest version of the library should let you see the error being returned from metamask (Even with a null message).

**Comment by Luzzotica** [comment]
I have created a custom contract call here: https://github.com/WalletConnect/Web3ModalFlutter/blob/2981053456ecd3511ca2e3a7f0def7c75e22af62/example/sign/lib/utils/crypto/eip155.dart#L197

Please mimic it for other SC calls.

**Comment by Hardu2203** [comment]
Hi Luzzotica,

Thank you for all the effort, I appreciate it.

I tried with the latest metamask version.  And it seems like it cannot find the return value `balance`?

![image](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/10627824/15e8bb31-7ee5-47ac-b767-3f79f5882db3)


Everything in the code looks fine to me, what wallet did you use while testing?

Also the transaction gets automatically rejected which is strange as well...

![image](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/10627824/9053c5a6-8504-4e92-bb61-b6bca627ee4b)
