### ISSUE TITLE
Wallet connect active network not showing

### ISSUE THREAD

**Issue by rashmisridar** [WalletConnect/WalletConnectModalFlutter#14]
Hi Team,
Connected the wallet successfully

 Not retuning the active network .
Example:-
If I change the network from Ethernet to Polygon then in the response I get both the network name . Active one is not showing .
Please let me know the solution for this. Thanks

**Comment by Luzzotica** [comment]
Changing the network _after_ the connection has taken place will do nothing.

You have to disconnect and reconnect for your chain swap to take place.

Let me add that to the docs.
