### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kuwogv** [WalletConnect/WalletConnectModalFlutter#19]
![1491692784273_ pic](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/13127929/935f4acb-58d5-43ad-863a-78c468c085cd)

**Comment by Sameerkash** [comment]
@kuwogv 

make sure you run `dart run build_runner build --delete-conflicting-outputs`
before running the project

**Comment by kuwogv** [comment]
thank you!
