### ISSUE TITLE
Not adapt to bottom safe area

### ISSUE THREAD

**Issue by AscenX** [WalletConnect/WalletConnectModalFlutter#23]
**Describe the bug**
The pop up sheet not adapt to bottom safe area.
version 2.1.5

**Screenshots**
![IMG_2386](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/12394822/a3f7f58d-f7d6-4874-8a6c-c3d43e3d9563)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16

**Comment by Sameerkash** [comment]
Helllo @AscenX! Can you also the screenshot of what you're expecting ?
