### ISSUE TITLE
Cannot connect to ETH wallet on latest version

### ISSUE THREAD

**Issue by rhbrunetto** [WalletConnect/WalletConnectModalFlutter#26]
**Describe the bug**
Can't connect with wallet either by modal or qrcode: the modal won't finish loading to display available wallets **and** the QRCode does not trigger any authorization dialog when scanned on Metamask.

**To Reproduce**
Steps to reproduce the behavior **on the example app**:
1. Open the example app
2. Select "Ethereum" on the chain list
3. Click on "Connect wallet" button
4. The modal won't finish loading

**Also, when you scan the generated QR code on Metamask, nothing happens. No dialog shows up to ask for authorization.**

Am I missing something?

**Expected behavior**
A list of wallets showing up on the modal and a authorization dialog popping up on Metamask after scanning the QrCode.

<details><summary>Screenshot</summary>

![Screenshot_1693834257](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/19499575/652d4fa2-08cb-4ec1-a05d-5987c10804ee)

</details>

**Smartphone:**
<details><summary>iOS</summary>

 - Device: iPhone 14 Pro max
 - OS: iOS 16.6
 
 -</details>

<details><summary>Android</summary>

 - Device: gphone64_arm64 (Emulated)
 - OS: Android 13
 - Version: Tiramisu
  
</details>

**Additional context**
No exception is thrown, no uncaught errors happen.

**Comment by Hardu2203** [comment]
Modal to connect works fine for me with the latest Metamask?

Are you specified your project_id correctly?

--dart-define=PROJECT_ID=<XXXXXXXXXXXX>

**Comment by rhbrunetto** [comment]
> Modal to connect works fine for me with the latest Metamask?
> 
> Are you specified your project_id correctly?
> 
> --dart-define=PROJECT_ID=XXXXXXXXXXXX

Yes, I'm using this config on VsCode:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "dev",
      "request": "launch",
      "type": "dart",
      "program": "lib/main.dart",
      "args": [
        "--dart-define",
        "PROJECT_ID=123456789123"
      ]
    }
  ]
}
```

**Comment by quetool** [comment]
Hello @rhbrunetto! `PROJECT_ID` must be a valid project ID over WalletConnect cloud. You can create a new project over here https://cloud.walletconnect.com/, after that you will be provided with a project ID. More details here https://docs.walletconnect.com/2.0/cloud/explorer#setting-up-a-new-project

You don't need to publish your project to test out your development but in case you wonder what one should do to publish their project you can read the guidelines here https://walletconnect.com/guidelines

**Comment by rhbrunetto** [comment]
Thank you so much for letting me know! That was pretty much the issue.
