### ISSUE TITLE
I can't retrieve the wallets in the modal

### ISSUE THREAD

**Issue by SyZenDev** [WalletConnect/WalletConnectModalFlutter#28]
Hi Luzzotica

I can't retrieve the wallets in the modal. Infinite loading plus error message in console 

Select Ethereum chain click on Connect Wallet Then an infinite loading appears 

![IMG_0854](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/144117133/440127cf-5881-4104-b57a-49bdb4b700f3)
<img width="1405" alt="Capture d’écran 2023-09-05 à 12 03 04" src="https://github.com/WalletConnect/WalletConnectModalFlutter/assets/144117133/702a4b2b-ec50-488b-89d6-dc88dad0ce74">
<img width="1405" alt="Capture d’écran 2023-09-05 à 12 03 12" src="https://github.com/WalletConnect/WalletConnectModalFlutter/assets/144117133/7f26406c-5be1-414b-89fc-f4739225f442">
<img width="1413" alt="Capture d’écran 2023-09-05 à 12 03 20" src="https://github.com/WalletConnect/WalletConnectModalFlutter/assets/144117133/b05ae18f-b63a-4b3b-ad26-9bb0951478d5">

Apple M2 Pro
Mac os 13.2 (22D49)

**Comment by quetool** [comment]
Hello @SyZenDev ! 
Can you please confirm you have valid project ID set up? See this issue for context https://github.com/WalletConnect/WalletConnectModalFlutter/issues/26

**Comment by SyZenDev** [comment]
Hi @quetool 

Thank you for your responsiveness, I did indeed have an error in my projectId

**Comment by quetool** [comment]
Glad we sorted it out! Feel free to close the issue if you consider it solved! 🎉
