### ISSUE TITLE
Timeout Exception 

### ISSUE THREAD

**Issue by emrekaya035** [WalletConnect/WalletConnectModalFlutter#29]
**Describe the bug**
When wallets are seeming in the screen, I click Metamask but the exception is throwing in VSC: 
"Exception has occurred. TimeoutException (TimeoutException after 0:00:00.000000: Future not completed)"

**To Reproduce**
For the example repository (in WalletConnectModalFlutter)
1. Click on 'Etherum' chain
2. Click on 'Connect Wallet' button
3. Click on 'Metamask' wallet button
4. The error is showing:
![image](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/72754835/37dadf95-3902-4d2b-8a42-70a1f6da103b)

**Smartphone and Flutter details:**
 - Device: [Pixel 3 API 28]
 - Dart: 3.0.5
 - Flutter: 3.10.5

**I tried "2.1.7", "2.1.5", "2.1.4" version of WalletConnectModalFlutter package but the error is still going.**

**Comment by quetool** [comment]
Hello @emrekaya035 ! Can you please confirm that by **unchecking** "Uncaught Exceptions" checkbox on VSCode you can move forward? (also continue execution should be fine)

![Screenshot 2023-09-05 at 18 01 29](https://github.com/WalletConnect/WalletConnectModalFlutter/assets/14978705/95cba82c-10c5-4795-ba9a-cff340b7c32d)

**Comment by emrekaya035** [comment]
Hi @quetool,
In VSCode the "Uncaught Exceptions" checkbox was check and I unchecked it.
Thanks for response, it worked.

**Comment by quetool** [comment]
@emrekaya035 thanks for confirming that. Just to be clear, it's good to have that checkbox checked as it will help you identify exceptions. I wanted to be sure that indeed by temporarily disabling it you were able to move forward. You can also move forward by clicking your run ▶️ button on VSCode (or F5 key if running from command line).
