### ISSUE TITLE
2 repositories

### ISSUE THREAD

**Issue by Hanul** [WalletConnect/WalletConnectModalFlutter#3]
What is the difference with the repository below?
https://github.com/WalletConnect/Web3ModalFlutter

**Comment by Luzzotica** [comment]
WalletConnectModal is a simple library that wraps WalletConnectV2 and makes it easy to connect to wallets.

WalletConnectModal is completely chain agnostic.

Web3Modal is (to my knowledge) reliant on EVM, and has a built in account page that will query the chain you are connected to, get the balance of their account, and offer other helper methods to make things easier when working with EVM based chains.
