### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Hardu2203** [WalletConnect/WalletConnectModalFlutter#7]
Please create an example of how to sign/send a transaction

**Comment by Luzzotica** [comment]
I am working on adding more in depth examples to the modal code.

In the meantime, the WalletConnectFlutterV2 library has examples for EVM chains [here](https://github.com/WalletConnect/WalletConnectFlutterV2/blob/master/example/dapp/lib/utils/crypto/eip155.dart)
